authors:
  emilc:
    name: Emil Frang Christiansen
    description: Senior NORTEM engineer
    avatar: https://backends.it.ntnu.no/user-profile-service/rest/files/f4da3c94-38e9-3a6c-bb14-6888d71499ac
    url: https://www.ntnu.no/ansatte/emil.christiansen